function step1a_preprocess(opts)

timerA=tic;

fprintf('Step 1a: Prepare... ');

%I would like to read the .prb file, but not sure about the format... it's
%not quite JSON... looks like javascript? Instead, hard-code locations
%below
%prb_in='raw/ms11.prb';
locations_out=opts.locations;
adjacency_out=opts.adjacency;

L=[...
0.0,0.0;...
-0.5,1.0;...
0.5,1.0;...
-1.0,2.0;...
1.0,2.0;...
-1.0,3.0;...
1.0,3.0;...
-1.0,4.0;...
1.0,4.0;...
-1.0,5.0;...
1.0,5.0;...
-1.0,6.0;...
1.0,6.0;...
-1.0,7.0;...
1.0,7.0;...
-1.0,8.0;...
1.0,8.0;...
-1.0,9.0;...
];
N=size(L,1);
fprintf('N=%d... \n',N);

fprintf('Writing %s... ',locations_out);
writemda(L,locations_out);

fprintf('Creating adjacency matrix... ');
radius=1.5;
AM=zeros(N,N);
for i1=1:N
    for i2=1:N
        diff0=L(i1,:)-L(i2,:);
        dist0=sqrt(diff0*diff0');
        if (dist0<=radius) AM(i1,i2)=1; end;
    end;
end;

fprintf('Writing %s... \n',adjacency_out);
writemda(AM,adjacency_out);

% if (opts.verbose)
%     fff=figure; imagesc(AM);
%     title(sprintf('Adjacency matrix using radius=%g',radius));
%     drawnow;
% end;

fprintf('\nElapsed: %g seconds',toc(timerA));
fprintf('\n');

end
